using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Http.Resilience;
using Moneyball.API.Background_Services;
using Moneyball.Core.Interfaces.ExternalAPIs;
using Moneyball.Core.Interfaces.ExternalServices;
using Moneyball.Core.Interfaces.Repositories;
using Moneyball.Infrastructure.ExternalAPIs.Odds;
using Moneyball.Infrastructure.ExternalAPIs.SportsRadar;
using Moneyball.Infrastructure.ExternalServices;
using Moneyball.Infrastructure.Repositories;
using Polly;
using System.Reflection;

namespace Moneyball.API;

public static class ServiceCollectionExtensions
{
    extension(IServiceCollection services)
    {
        public void ConfigureBackgroundServices(IConfiguration configuration)
        {
            if (configuration.GetValue<bool>("DataIngestion:EnableBackgroundService"))
            {
                services.AddHostedService<DataIngestionBackgroundService>();
            }
        }

        public void ConfigureCors()
        {
            services.AddCors(options =>
            {
                options.AddPolicy("AllowAll",
                    policyBuilder =>
                    {
                        policyBuilder.AllowAnyOrigin()
                            .AllowAnyMethod()
                            .AllowAnyHeader();
                    });
            });
        }

        public void ConfigureDatabase(IConfiguration configuration)
        {
            // Database Context with retry policies
            services.AddDbContext<MoneyballDbContext>(options =>
                options.UseSqlServer(
                    configuration.GetConnectionString("DefaultConnection"),
                    sqlOptions => sqlOptions.EnableRetryOnFailure(
                        maxRetryCount: 5,
                        maxRetryDelay: TimeSpan.FromSeconds(30),
                        errorNumbersToAdd: null)));
        }

        public void ConfigureHttpClients(IConfiguration configuration)
        {
            var sportsDataBaseUrl = configuration["SportsData:BaseUrl"] ?? "https://api.sportradar.com/nba/trial/v8/en";

            // HTTP Clients with Polly retry policies
            services.AddHttpClient<ISportsDataService, SportsDataService>(c =>
                    c.BaseAddress = new Uri(sportsDataBaseUrl))
                .AddResilienceHandler("sports-data-pipeline", ConfigureResiliencePipeline);

            var oddsDataBaseUrl = configuration["OddsAPI:BaseUrl"] ?? "https://api.the-odds-api.com/v4";

            services.AddHttpClient<IOddsDataService, OddsDataService>(c =>
                    c.BaseAddress = new Uri(oddsDataBaseUrl))
                .AddResilienceHandler("odds-data-pipeline", ConfigureResiliencePipeline);
        }

        public void ConfigureRepositories()
        {
            //services.AddScoped<IGameOddsRepository, GameOddsRepository>();
            //services.AddScoped<IRepository<GameOdds>, Repository<GameOdds>>();
            //services.AddScoped<IGameRepository, GameRepository>();
            //services.AddScoped<IModelRepository, ModelRepository>();
            services.AddScoped<IMoneyballRepository, MoneyballRepository>();
            //services.AddScoped<IPredictionRepository, PredictionRepository>();
            //services.AddScoped<ITeamRepository, TeamRepository>();
        }

        public void ConfigureServices()
        {
            // External APIs
            services.AddScoped<ISportsDataService, SportsDataService>();
            services.AddScoped<IOddsDataService, OddsDataService>();

            // Data Services
            services.AddScoped<IDataIngestionService, DataIngestionService>();
            services.AddScoped<IDataIngestionOrchestrator, DataIngestionOrchestrator>();
        }

        public void ConfigureSwagger()
        {
            services.AddSwaggerGen(options =>
            {
                // Locate the XML file being generated by ASP.NET...
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                // ... and tell Swagger to use those XML comments.
                options.IncludeXmlComments(xmlPath);
            });
        }
    }

    private static void ConfigureResiliencePipeline(ResiliencePipelineBuilder<HttpResponseMessage> pipeline)
    {
        // 1️⃣  Retry — 3 attempts, exponential back-off, on 5xx + 429
        pipeline.AddRetry(new HttpRetryStrategyOptions
        {
            MaxRetryAttempts = 3,
            BackoffType = DelayBackoffType.Exponential,
            UseJitter = true,          // avoids thundering-herd
            Delay = TimeSpan.FromSeconds(1),
            ShouldHandle = args =>
            {
                // Retry on any 5xx or HTTP 429 (Too Many Requests)
                if (args.Outcome.Result is { } response)
                    return ValueTask.FromResult(
                        (int)response.StatusCode >= 500 ||
                        response.StatusCode == System.Net.HttpStatusCode.TooManyRequests);

                return ValueTask.FromResult(args.Outcome.Exception is not null);
            }
        });

        // 2️⃣  Circuit Breaker — opens after 5 consecutive failures
        pipeline.AddCircuitBreaker(new HttpCircuitBreakerStrategyOptions
        {
            FailureRatio = 1.0,   // 100 % of requests in the window must fail
            MinimumThroughput = 5,     // …across at least 5 requests
            SamplingDuration = TimeSpan.FromSeconds(30),
            BreakDuration = TimeSpan.FromSeconds(15),
            ShouldHandle = args =>
            {
                if (args.Outcome.Result is { } response)
                    return ValueTask.FromResult(
                        (int)response.StatusCode >= 500 ||
                        response.StatusCode == System.Net.HttpStatusCode.TooManyRequests);

                return ValueTask.FromResult(args.Outcome.Exception is not null);
            },
            OnOpened = args =>
            {
                // Optional: log / alert when the breaker trips
                Console.WriteLine($"Circuit opened for {args.BreakDuration}");
                return ValueTask.CompletedTask;
            }
        });
    }
}