// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moneyball.Infrastructure.Repositories;

#nullable disable

namespace Moneyball.Infrastructure.Migrations
{
    [DbContext(typeof(MoneyballDbContext))]
    partial class MoneyballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Moneyball.Core.Entities.BettingRecommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Edge")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("KellyFraction")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("MinBankroll")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PredictionId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedBetType")
                        .HasColumnType("int");

                    b.Property<decimal>("RecommendedStakePercentage")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("RecommendedTeamId")
                        .HasColumnType("int");

                    b.HasKey("RecommendationId");

                    b.HasIndex("PredictionId");

                    b.HasIndex("RecommendedTeamId");

                    b.HasIndex("Edge", "CreatedAt");

                    b.ToTable("BettingRecommendations", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalGameId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Week")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("ExternalGameId");

                    b.HasIndex("GameDate");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SportId", "GameDate");

                    b.HasIndex("Status", "GameDate");

                    b.ToTable("Games", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModelId");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.HasIndex("SportId", "IsActive");

                    b.ToTable("Models", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.ModelPerformance", b =>
                {
                    b.Property<int>("PerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerformanceId"));

                    b.Property<decimal?>("Accuracy")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ROI")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("int");

                    b.HasKey("PerformanceId");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelPerformances", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Odds", b =>
                {
                    b.Property<int>("OddsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OddsId"));

                    b.Property<decimal?>("AwayMoneyline")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AwaySpread")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AwaySpreadOdds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BookmakerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<decimal?>("HomeMoneyline")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HomeSpread")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HomeSpreadOdds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("OverOdds")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("OverUnder")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UnderOdds")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OddsId");

                    b.HasIndex("BookmakerName");

                    b.HasIndex("GameId", "RecordedAt");

                    b.ToTable("GameOdds", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Prediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Edge")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("FeatureValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PredictedAwayScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PredictedAwayWinProbability")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("PredictedHomeScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PredictedHomeWinProbability")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("PredictedTotal")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PredictionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GameId", "ModelId");

                    b.HasIndex("ModelId", "CreatedAt");

                    b.ToTable("Predictions", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SportId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sports", "dbo");

                    b.HasData(
                        new
                        {
                            SportId = 1,
                            IsActive = true,
                            Name = "NBA"
                        },
                        new
                        {
                            SportId = 2,
                            IsActive = true,
                            Name = "NFL"
                        },
                        new
                        {
                            SportId = 3,
                            IsActive = true,
                            Name = "NHL"
                        },
                        new
                        {
                            SportId = 4,
                            IsActive = true,
                            Name = "MLB"
                        });
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Conference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("Name");

                    b.HasIndex("SportId", "ExternalId");

                    b.ToTable("Teams", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.TeamStatistic", b =>
                {
                    b.Property<int>("TeamStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamStatisticId"));

                    b.Property<string>("AdditionalStats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("Blocks")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefensiveRebounds")
                        .HasColumnType("int");

                    b.Property<decimal?>("FieldGoalPercentage")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("FieldGoalsAttempted")
                        .HasColumnType("int");

                    b.Property<int?>("FieldGoalsMade")
                        .HasColumnType("int");

                    b.Property<decimal?>("FreeThrowPercentage")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("FreeThrowsAttempted")
                        .HasColumnType("int");

                    b.Property<int?>("FreeThrowsMade")
                        .HasColumnType("int");

                    b.Property<int?>("Fumbles")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("int");

                    b.Property<bool>("IsHomeTeam")
                        .HasColumnType("bit");

                    b.Property<int?>("OffensiveRebounds")
                        .HasColumnType("int");

                    b.Property<int?>("PassingYards")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalFouls")
                        .HasColumnType("int");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("Rebounds")
                        .HasColumnType("int");

                    b.Property<int?>("RushingYards")
                        .HasColumnType("int");

                    b.Property<int?>("Sacks")
                        .HasColumnType("int");

                    b.Property<int?>("Steals")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThreePointPercentage")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("ThreePointsAttempted")
                        .HasColumnType("int");

                    b.Property<int?>("ThreePointsMade")
                        .HasColumnType("int");

                    b.Property<decimal?>("TimeOfPossession")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TotalYards")
                        .HasColumnType("int");

                    b.Property<int?>("Touchdowns")
                        .HasColumnType("int");

                    b.Property<int?>("Turnovers")
                        .HasColumnType("int");

                    b.HasKey("TeamStatisticId");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameId", "TeamId");

                    b.ToTable("TeamStatistics", "dbo");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.BettingRecommendation", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Prediction", "Prediction")
                        .WithMany("Recommendations")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moneyball.Core.Entities.Team", "RecommendedTeam")
                        .WithMany()
                        .HasForeignKey("RecommendedTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Prediction");

                    b.Navigation("RecommendedTeam");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Game", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moneyball.Core.Entities.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Moneyball.Core.Entities.Sport", "Sport")
                        .WithMany("Games")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Model", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Sport", "Sport")
                        .WithMany("Models")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.ModelPerformance", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Model", "Model")
                        .WithMany("PerformanceRecords")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Odds", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Game", "Game")
                        .WithMany("Odds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Prediction", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Game", "Game")
                        .WithMany("Predictions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Moneyball.Core.Entities.Model", "Model")
                        .WithMany("Predictions")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Team", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Sport", "Sport")
                        .WithMany("Teams")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.TeamStatistic", b =>
                {
                    b.HasOne("Moneyball.Core.Entities.Game", "Game")
                        .WithMany("TeamStatistics")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moneyball.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Game", b =>
                {
                    b.Navigation("Odds");

                    b.Navigation("Predictions");

                    b.Navigation("TeamStatistics");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Model", b =>
                {
                    b.Navigation("PerformanceRecords");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Prediction", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Sport", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Models");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Moneyball.Core.Entities.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");
                });
#pragma warning restore 612, 618
        }
    }
}
